"""add_foreign_currency_fields

Revision ID: 64f52b1c4310
Revises: b2c3d4e5f6g7
Create Date: 2025-11-23 13:19:07.203706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f52b1c4310'
down_revision = 'b2c3d4e5f6g7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('foreign_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('foreign_currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'foreign_currency')
    op.drop_column('transactions', 'foreign_amount')
    # ### end Alembic commands ###
